Matplotlib created a temporary config/cache directory at /tmp/matplotlib-mz3h_p7p because the default path (/home/mriqc/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-fctkme_1 because the default path (/home/mriqc/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zjkqn3cu because the default path (/home/mriqc/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mriqc/cli/run.py", line 159, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 184, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node EPI2MNI.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 399, in run
    runtime = self._post_run_hook(runtime)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/reportlets/registration.py", line 81, in _post_run_hook
    return super(SpatialNormalizationRPT, self)._post_run_hook(runtime)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/reportlets/base.py", line 92, in _generate_report
    plot_registration(
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/viz/utils.py", line 385, in plot_registration
    svg = extract_svg(display, compress=compress)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/viz/utils.py", line 140, in extract_svg
    image_svg = svg2str(display_object, dpi)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/viz/utils.py", line 132, in svg2str
    display_object.frame_axes.figure.savefig(
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 389, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/backends/backend_svg.py", line 1333, in print_svg
    self.figure.draw(renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/figure.py", line 2837, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3091, in draw
    mimage._draw_list_compositing_images(
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 156, in _draw_list_compositing_images
    flush_images()
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 140, in flush_images
    image_group[0].draw(renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 557, in _make_image
    output = _resample(  # resample rgb channels
  File "/opt/conda/lib/python3.9/site-packages/matplotlib/image.py", line 190, in _resample
    out = np.zeros(out_shape + data.shape[2:], data.dtype)  # 2D->2D, 3D->3D.
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 97.3 MiB for an array with shape (690, 4621, 4) and data type float64


